// Re-export shared types for client use
export type {
  LogEntry,
  LogEntryType,
  Account,
  AccountsState,
  WsMessage,
  SendRequest,
  BatchRequest,
  HistoryRequest,
  ZooAgentState,
  ZooPurchaseReceipt,
  PreflightCheck,
  PreflightResult,
  NetworkStats,
  TokenInfo,
  WalletInfo,
  BalanceHistoryEntry,
  TransactionDetail,
  TxFlowStage,
  TransactionFlowEvent,
  BalanceUpdate,
} from '../../shared/types.js';
